/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScansRouteImport } from './routes/scans'
import { Route as MartRouteImport } from './routes/mart'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ScansRoute = ScansRouteImport.update({
  id: '/scans',
  path: '/scans',
  getParentRoute: () => rootRouteImport,
} as any)
const MartRoute = MartRouteImport.update({
  id: '/mart',
  path: '/mart',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/farmer': typeof FarmerRoute
  '/marketplace': typeof MarketplaceRoute
  '/mart': typeof MartRoute
  '/scans': typeof ScansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/farmer': typeof FarmerRoute
  '/marketplace': typeof MarketplaceRoute
  '/mart': typeof MartRoute
  '/scans': typeof ScansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/farmer': typeof FarmerRoute
  '/marketplace': typeof MarketplaceRoute
  '/mart': typeof MartRoute
  '/scans': typeof ScansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/farmer' | '/marketplace' | '/mart' | '/scans'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/farmer' | '/marketplace' | '/mart' | '/scans'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/farmer'
    | '/marketplace'
    | '/mart'
    | '/scans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FarmerRoute: typeof FarmerRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MartRoute: typeof MartRoute
  ScansRoute: typeof ScansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scans': {
      id: '/scans'
      path: '/scans'
      fullPath: '/scans'
      preLoaderRoute: typeof ScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mart': {
      id: '/mart'
      path: '/mart'
      fullPath: '/mart'
      preLoaderRoute: typeof MartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FarmerRoute: FarmerRoute,
  MarketplaceRoute: MarketplaceRoute,
  MartRoute: MartRoute,
  ScansRoute: ScansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
